# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yuhan He
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Yuhan's blog!
baseurl: "" # the subpath of the site
url: "https://sime-chill.github.io/" # the base hostname & protocol for the site
og_image: /assets/img/pic_hyh3.png
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    # - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: yhhe23@m.fudan.edu.cn
      value: yhhe23@m.fudan.edu.cn
  follow:
    - type: github
      name: GitHub
      link: http://github.com/sime-chill


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1